[alias]
xtask = "run --manifest-path xtask/Cargo.toml --"

[build]
target = "wasm32-unknown-unknown"

# [target.'cfg(target_arch = "wasm32")']
# rustflags = ["--no-default-features --features webgpu"]
